export type CompatibilityStatus = 'supported' | 'partial' | 'unsupported'

export interface Capability {
  status: CompatibilityStatus
  note: string
}

export const extensionApiCapabilities = {
  registerTool: { status: 'partial', note: 'Execution, fail-closed schema projection including disjoint literal unions and numeric bounds (minimum/maximum/exclusiveMinimum/minItems), cancellation, sanitized errors, bounded results, ordered updates, images, lifecycle-time registration/replacement, active-tool changes, and concurrency map; unsupported validation keywords, Pi renderers, and DSH streaming UI do not.' },
  registerCommand: { status: 'partial', note: 'Slash command handlers, sanitized unexpected failures, and notify text (captured and returned as the command result, not streamed live) map; argument completions do not. Dialogs inside commands use the visible UI bridge when a decision path is composed.' },
  registerShortcut: { status: 'unsupported', note: 'DSH has no plugin-owned keyboard shortcut registry.' },
  registerFlag: { status: 'supported', note: 'Defaults and configured overrides use the Pi runner.' },
  getFlag: { status: 'supported', note: 'Uses the Pi runner flag store.' },
  registerMessageRenderer: { status: 'unsupported', note: 'Pi TUI components are not replayable DSH render intents.' },
  registerEntryRenderer: { status: 'unsupported', note: 'Pi TUI components are not replayable DSH render intents.' },
  sendMessage: { status: 'partial', note: 'Every custom entry is durably appended to the projected Pi session before delivery; workflow messages dedupe by workflowMessageId and duplicates are not re-enqueued. Non-waking idle injection, trigger-turn, follow-up, steering, and native next-turn delivery map; display/details are persisted in the Pi projection.' },
  sendUserMessage: { status: 'supported', note: 'Text and image messages map to DSH followup or steering with durable attachments.' },
  appendEntry: { status: 'partial', note: 'Persisted in the durable projected Pi session; not written into the DSH event log.' },
  setSessionName: { status: 'partial', note: 'Appends to the projected Pi session; DSH title projection is not changed.' },
  getSessionName: { status: 'partial', note: 'Returns the Pi-side projected session name.' },
  setLabel: { status: 'partial', note: 'Stored in the projected Pi session tree only.' },
  exec: { status: 'supported', note: 'Uses Pi coding-agent exec with cwd, environment, timeout, and cancellation options.' },
  getActiveTools: { status: 'partial', note: 'Returns the filtered active set of adapted Pi tools, excluding DSH-native tools.' },
  getAllTools: { status: 'partial', note: 'Uses the Pi extension registry; DSH-native tools are not included.' },
  setActiveTools: { status: 'partial', note: 'Reconciles adapted Pi tools and ignores unknown names, but does not toggle DSH-native tools.' },
  getCommands: { status: 'partial', note: 'Uses the Pi extension command registry; DSH-native commands, skills, and templates are not included.' },
  setModel: { status: 'partial', note: 'Maps provider/id onto DSH agent options; availability is still owned by DSH adapters.' },
  getThinkingLevel: { status: 'partial', note: 'Pi-side state only.' },
  setThinkingLevel: { status: 'partial', note: 'Pi-side state only; DSH reasoning effort is not changed.' },
  registerProvider: { status: 'unsupported', note: 'A Pi provider is not a DSH LlmAdapter; configure dsh-llm-pi-ai separately.' },
  unregisterProvider: { status: 'unsupported', note: 'No DSH adapter ownership is created by the host.' },
  events: { status: 'supported', note: 'The shared Pi EventBus is supplied by the official loader.' },
} as const satisfies Record<string, Capability>

export const extensionContextCapabilities = {
  ui: { status: 'partial', note: 'Text notifications, statuses, and widget clears publish visibly into the DSH session; select/confirm/input/editor dialogs route through ctx.userQuestions when composed, and unavailable decisions fail visibly. Terminal components and theme controls are unsupported.' },
  mode: { status: 'partial', note: 'Reports the embedded Pi runtime mode (rpc with a decision path, otherwise print), not the active DSH client frontend.' },
  hasUI: { status: 'supported', note: 'Dynamically reflects whether a real DSH dialog decision path is available, never mere text publication.' },
  cwd: { status: 'supported', note: 'Uses the DSH agent session working directory.' },
  sessionManager: { status: 'partial', note: 'A durable Pi session projection is mounted per DSH session under ~/.dsh/pi-sessions; native DSH turns are projected into its branch (text blocks only) and workflow identities persist across restart. Images and full model metadata are not projected.' },
  modelRegistry: { status: 'partial', note: 'getAll/getAvailable/find/refresh read a refreshed snapshot of the DSH model catalog (provider/id/name with conservative bounds); credentials, auth status, and Pi provider registration remain unexposed.' },
  model: { status: 'partial', note: 'Projects the current DSH agent selection as provider/id; Pi model metadata (cost, windows, modalities) is not exposed.' },
  isIdle: { status: 'supported', note: 'Reads the DSH agent status.' },
  isProjectTrusted: { status: 'supported', note: 'Returns the explicit projectTrusted configuration decision.' },
  signal: { status: 'supported', note: 'Invocation-scoped DSH cancellation is exposed to Pi handlers and tools.' },
  abort: { status: 'supported', note: 'Cancels the current DSH agent operation.' },
  hasPendingMessages: { status: 'supported', note: 'Reads the DSH agent inbox.' },
  shutdown: { status: 'partial', note: 'Cancels the current DSH agent operation; it does not terminate the DSH process.' },
  getContextUsage: { status: 'unsupported', note: 'DSH token usage is not projected into the Pi ContextUsage shape.' },
  compact: { status: 'unsupported', note: 'DSH compaction has a different lifecycle and is not invoked.' },
  getSystemPrompt: { status: 'unsupported', note: 'The effective DSH prompt is not exposed through the Pi context.' },
  getSystemPromptOptions: { status: 'partial', note: 'Command contexts receive cwd only.' },
  waitForIdle: { status: 'supported', note: 'Command contexts wait on the owning DSH agent settlement.' },
  newSession: { status: 'unsupported', note: 'Pi session replacement is not mapped to DSH agent creation and fails explicitly.' },
  fork: { status: 'unsupported', note: 'Pi session-tree fork is not mapped and fails explicitly.' },
  navigateTree: { status: 'unsupported', note: 'Pi session-tree navigation is not mapped and fails explicitly.' },
  switchSession: { status: 'unsupported', note: 'Pi session switching is not mapped and fails explicitly.' },
  reload: { status: 'unsupported', note: 'Pi resource reload is not mapped to DSH plugin reload and fails explicitly.' },
} as const satisfies Record<string, Capability>

export const extensionEventCapabilities = {
  project_trust: { status: 'partial', note: 'The configured trust decision controls ctx.isProjectTrusted; interactive trust handlers are not run.' },
  resources_discover: { status: 'partial', note: 'Pi handlers run, but returned skills/prompts/themes are not registered in DSH.' },
  session_start: { status: 'supported', note: 'Mapped from DSH agent/session-start and awaited before first pre-step; re-emitted after session_shutdown on DSH resume/clear/compact.' },
  session_info_changed: { status: 'unsupported', note: 'No DSH title projection listener yet.' },
  session_before_switch: { status: 'unsupported', note: 'No direct DSH session-switch veto point.' },
  session_before_fork: { status: 'unsupported', note: 'No direct DSH fork veto mapping yet.' },
  session_before_compact: { status: 'unsupported', note: 'DSH compaction owns a different contract.' },
  session_compact: { status: 'unsupported', note: 'Compact currently maps to a session_shutdown/session_start restart with reload semantics only.' },
  session_shutdown: { status: 'partial', note: 'Runs with the transition reason before each DSH resume/clear/compact restart; agent/plugin disposal still reports Pi reason quit.' },
  session_before_tree: { status: 'unsupported', note: 'Pi session-tree navigation has no DSH equivalent.' },
  session_tree: { status: 'unsupported', note: 'Pi session-tree navigation has no DSH equivalent.' },
  context: { status: 'unsupported', note: 'DSH request reconstruction is durable and cannot accept Pi mutable message arrays directly.' },
  before_provider_request: { status: 'unsupported', note: 'Provider payload mutation belongs to the DSH adapter boundary.' },
  before_provider_headers: { status: 'unsupported', note: 'Provider headers belong to the DSH adapter boundary.' },
  after_provider_response: { status: 'unsupported', note: 'No DSH response hook currently maps this event.' },
  before_agent_start: { status: 'partial', note: 'Runs once before the first DSH step; system-prompt replacement and returned custom messages are not applied yet.' },
  agent_start: { status: 'supported', note: 'Mapped once per DSH turn.' },
  agent_end: { status: 'partial', note: 'Mapped once from committed DSH turn/end, including failure paths; provider usage, images, and tool messages are reduced.' },
  agent_settled: { status: 'partial', note: 'Emitted after agent_end when the committed DSH turn has no pending inbox messages; queue semantics differ.' },
  turn_start: { status: 'supported', note: 'Mapped once per DSH step.' },
  turn_end: { status: 'partial', note: 'Paired with each DSH step, using committed turn/end for the final success, error, or cancellation boundary; Pi toolResults are not reconstructed.' },
  message_start: { status: 'unsupported', note: 'No per-message DSH live hook mapping yet.' },
  message_update: { status: 'unsupported', note: 'No Pi streaming event is synthesized from DSH chunks.' },
  message_end: { status: 'unsupported', note: 'Mutable Pi message replacement conflicts with DSH durable reconstruction.' },
  tool_execution_start: { status: 'supported', note: 'Emitted around adapted Pi tool execution.' },
  tool_execution_update: { status: 'partial', note: 'Pi handlers finish updates before the terminal event; DSH has no matching live tool-update callback.' },
  tool_execution_end: { status: 'supported', note: 'Paired with adapted Pi tool execution, including failures and cancellation.' },
  model_select: { status: 'unsupported', note: 'No DSH selection event mapping yet.' },
  thinking_level_select: { status: 'unsupported', note: 'No DSH reasoning-effort event mapping yet.' },
  tool_call: { status: 'partial', note: 'Blocking works; DSH freezes arguments, so Pi handlers cannot reliably mutate input in place.' },
  tool_result: { status: 'supported', note: 'Can replace Pi content/details/error before conversion to DSH.' },
  user_bash: { status: 'unsupported', note: 'DSH shell tools do not expose Pi user-bash interception semantics.' },
  input: { status: 'partial', note: 'Text/image transform and handled run once for the initial claimed DSH message batch; text is newline-joined and original message identities collapse on transform.' },
} as const satisfies Record<string, Capability>
